config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  # Add Devise routes for user authentication and registration
  devise_for :users

  resources :users, only: [:index, :show] do
    resources :posts, only: [:index, :show, :new, :create, :destroy] do
      resources :comments, only: [:new, :create, :destroy]
      resources :likes, only: [:create]
    end  
  end

  namespace :api, defaults: { format: :json } do
    resources :users, only: [:index] do
      resources :posts, only: [:index, :show] do
        resources :comments, only: [:index, :create]
      end
    end
  end

end

app/models/ability.rb
# ability.rb

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for guest users (not logged in)
    if user.nil?
      cannot :manage, :all
      can :show, Post
      can :index, Post
    end

    # Define abilities for logged-in users
    if user.present?
      # Abilities for all users
      can :show, Post
      can :index, Post

      # Abilities for the post author
      can :new, Post, author_id: user.id
      can :create, Post, author_id: user.id
      can :destroy, Post, author_id: user.id

      # Abilities for comments
      can :create, Comment, author_id: user.id
      can :destroy, Comment, author_id: user.id

      # Abilities for admin users
      if user.role == 'admin'
        can :destroy, Post
        can :destroy, Comment
      end
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  attribute :comment

  after_create :update_post_comment_counter
  after_destroy :update_post_comment_counter

  validates :comment, presence: true

  def update_post_comment_counter
    post.increment!(:comments_counter)
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  belongs_to :post, foreign_key: 'post_id'

  attribute :user_id

  after_create :update_post_likes_counter
  after_destroy :update_post_likes_counter

  def update_post_likes_counter
    post.update(likes_counter: post.likes.count)
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: { message: 'must be present' }
  validate :validate_title_length
  validates :comments_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }
  validates :likes_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  before_save :update_user_posts_counter

  def recent_comments
    comments.includes(:author).order(created_at: :desc).limit(5)
  end

  def update_user_posts_counter
    author.update(posts_counter: author.posts.count + 1)
  end

  def validate_title_length
    return unless title.present? && title.length > 250

    errors.add(:title, 'is too long (maximum is 250 characters)')
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts, foreign_key: :author_id, dependent: :destroy
  has_many :likes, foreign_key: :author_id, dependent: :destroy
  has_many :comments, foreign_key: :author_id, dependent: :destroy

  validates :posts_counter, numericality: { only_integer: true, greater_than_or_equal_to: 0, allow_nil: true }

  def recent_posts
    posts.order(created_at: :desc).limit(3)
  end

  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :validatable, :confirmable

  def admin?
    role == 'admin'
  end
end

app/controllers/api/comments_controller.rb
module Api
    class CommentsController < ApplicationController
      def index
        post = Post.find(params[:post_id])
        comments = post.comments
        render json: comments
      end
  
      def create
        post = Post.find(params[:post_id])
        comment = post.comments.new(comment_params)
        if comment.save
          render json: comment, status: :created
        else
          render json: { error: 'Failed to create comment' }, status: :unprocessable_entity
        end
      end
  
      private
  
      def comment_params
        params.require(:comment).permit(:body)
      end
    end
end

app/controllers/api/posts_controller.rb
module Api
    class PostsController < ApplicationController
      def index
        user = User.find(params[:user_id])
        posts = user.posts
        render json: posts
      end
  
      def show
        post = Post.find(params[:id])
        render json: post
      end
    end
end

app/controllers/api/users_controller.rb
module Api
    class UsersController < ApplicationController
      def index
        users = User.all
        render json: users
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def current_ability
        @current_ability ||= Ability.new(current_user)
    end
    
    # Delegate `can?` method to the `current_ability`
    def can?(action, subject)
        current_ability.can?(action, subject)
    end
    helper_method :can?
end
  

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :load_post_and_user, only: [:new, :create]
  load_and_authorize_resource except: [:new, :create]

  def new
    @comment = Comment.new
    puts "@user: #{@user}, @post: #{@post}, @comment: #{@comment}"
    render :new, locals: { comment: @comment, post: @post }
  end

  def create
    @comment = Comment.new(comment_params)
    @comment.author = @user
    @comment.post = @post

    if @comment.save
      redirect_to user_post_path(@user, @post), notice: 'Comment was successfully created.'
    else
      flash.now[:errors] = @comment.errors.full_messages
      render :new
    end
  end

  def destroy
    @comment.destroy
    redirect_to request.referrer, notice: 'Your comment was successfully deleted!'
  end

  private

  def load_post_and_user
    @post = Post.includes(:author).find(params[:post_id])
    @user = current_user
  end

  def comment_params
    params.require(:comment).permit(:comment)
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    @user = current_user
    @like = Like.new(author: @user, post: @post)

    @like.save
    redirect_to user_post_path(@user.id, @post)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  before_action :set_user, only: [:new, :create]
  before_action :authenticate_user!, only: [:new]

  def index
    @user = User.includes(posts: :comments).find(params[:user_id])
    @posts = @user.posts
    @comments = Comment.where(post_id: @posts.pluck(:id))
  end

  def show
    @post = Post.find(params[:id])
    @users = @post.author
    @index = @users.posts.order(created_at: :asc).pluck(:id).index(@post.id)
  end

  def new
    @post = @user.posts.build
  end

  def set_user
    @user = current_user
  end

  def create
    @user = @current_user
    @post = Post.new(post_params.merge(author_id: @user.id))

    if @post.save
      redirect_to user_posts_url(@user)
    else
      render :new
    end
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to user_path(@post.author), notice: 'Post deleted successfully'
  end

  private

  def post_params
    params.require(:post).permit(:title, :description)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]

  def index
    @users = User.all
  end

  def show
    @user = User.includes(posts: %i[comments likes]).find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_form.html.erb
<%= form_with model: [@current_user, @post, Comment.new], url: user_post_comments_path(@current_user, @post), class: 'comment_form' do |form| %>
    <div class="form">
      <%= form.text_area :comment, class: 'form-control comment_input', placeholder: 'Enter your comment here' %>
        <% form.object.errors.full_messages_for(:comment).each do |message| %>
        <div class="error-message"><%= message %></div>
      <% end %>
    </div>
    <%= form.submit 'Submit' %>
<% end %>

app/views/comments/new.html.erb
<div class="comment-form">
  <div class="page-title">
    <h2>Post your thoughts</h2>
  </div>

  <%= form_with model: @comment, url: user_post_comments_path(@user, @post) do |form| %>
    <div class="form">
      <div class="comment">
        <%= form.text_field :comment, required: true, placeholder: "Enter your comment" %>
      </div>
      <div class="submit">
        <%= form.submit "Submit" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Techbright</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "style" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/index.html.erb
<div class="user-posts">
  <div class="user-details">
    <div class="user-image">
      <img src="<%= @user.image %>" class="image">
    </div>

    <div class="user-info">
      <h2><%= link_to @user.name, user_path(@user) %></h2>
      <p>Number of posts: <%= @user.posts.count %></p>
    </div>
  </div>

  <!-- posts/index.html.erb -->
  <% @posts.each_with_index do |post, index| %>
    <div class="posts">
      <b>Post #<%= index + 1 %></b>
      <p class="post-text">
        <%= link_to truncate(post.description, length: 20), user_post_path(post.author, post) %>
      </p>
      <% if can? :destroy, post %>
      <%= button_to "Delete", user_post_path(post.author, post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
    <% end %>
      <div class="coutner-cont">
        <h6>Comments: <%= post.comments.count %></h6>
        <h6>Likes: <%= post.likes.count %></h6>
      </div>

      <% post.recent_comments.each do |comment| %>
        <p><%= comment.author.name %>: <%= comment.comment %></p>
       
      <% end %>
    </div>
  <% end %>

  <button class="pagination">Pagination</button>

</div>

app/views/posts/new.html.erb
<div class="add-post-form">
    <div class="page-title">
        <h1>Add new post</h1>
    </div>

   <!-- posts/new.html.erb -->
<div class="form">
  <%= form_with model: [@user, @post], url: user_posts_path(current_user), local: true do |form| %>
    <div class="title">
      <label for="title">Title</label>
      <%= form.text_field :title %>
    </div>

    <div class="description">
      <label for="description">Description</label>
      <%= form.text_area :description %>
    </div>

    <%= form.submit "Create Post" %>
  <% end %>
</div>

  
</div>

app/views/posts/show.html.erb
<div class="post-details">
    <div class="posts">
        <div class="items">
            <b>Post #<%= @index + 1 %> by <%=link_to @users.name, "/users" %></b>
            <div class="likes-comments">
            <h5>Comments: <%= @post.comments.count %></h5>
            <h5>Likes: <%= @post.likes.count %></h5>
        </div>
    </div>
    <p class="post-description">
        <b><%= @post.title %></b><br><br>
        <%= @post.description %>
        <% if can? :destroy, @post %>
    <%= button_to "Delete", user_post_path(@post.author, @post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" } %>
  <% end %>
    </p>
    <% @post.comments.each do |comment| %>
        <p><%= comment.author.name %>: <%= comment.comment %></p>
        <% if can? :destroy, comment %>
        <%= button_to "Delete", user_post_comment_path(@post.author, @post, comment), method: :delete, data: { confirm: "Are you sure you want to delete this comment?" } %>
      <% end %>
    <% end %>

    <div class="comment-form">
        <button type="button">
            <%= link_to "Comment", new_user_post_comment_path(post_id: @post.id) %>
        </button>
    </div>
    <br><br>
    <div class="like-button">
        <%= form_with model: @like, url: user_post_likes_path(1, @post), scope: :like do |form| %>
            <%= form.submit "Like" %>
        <% end %>
    </div>
</div>

app/views/users/index.html.erb
<div class="users-list">
    <% @users.each do |user| %>
        <div class="user">
            <div class="image">
                <% if user.image.present? %>
                    <%= image_tag(user.image, class: "user-img") %>
                <% else %>
                    <%= image_tag("no-image-found.png", class: "user-img") %>
                <% end %>
            </div>
            <div class="details">
                <a href="/users/<%= user.id %>"><h2><%= user.name %></h2></a>
                <h4>Number of posts: <%= user.posts_counter %></h4>
            </div>
        </div>
    <% end %>
</div>

app/views/users/show.html.erb
<div class="user-details">
    <div class="details">
        <div class="user-image">
            <%= image_tag(@user.image, class: 'img') %>
        </div>
        <div class="name">
            <h2><%= @user.name %></h2>
            <h5>Number of posts: <%= @user.posts_counter %></h5>
        </div>
    </div>
    <div class="bio">
        <h3>Bio</h3>
        <p><%= @user.bio %></p>
    </div>

    <% @user.recent_posts.each do |post| %>
        <div class="recent-posts">
            <%= link_to post.title, user_post_path(@user, post) %>
            <p><%= post.description %></p>
            <div class="like-comment">
                <span class="comment">Comments: <%= post.comments_counter %></span> 
                <span class="like"span>Likes: <%= post.likes_counter %></span>
            </div>
        </div>
        <br><br>
    <% end %>

    <div class="see-posts">
        <a href="/users/<%= @user.id %>/posts" id="user-btn">See all posts</a>
    </div>
</div>